### ISSUE TITLE
Some problem about the paper

### ISSUE THREAD

**Issue by JasonCZH4** [zhaoyiran924/Adv-In-Context-Learning#3]
I like your work. Your work is the first to introduce the idea of adversarial training into prompt optimization. It's very interesting. However, I have few questions.
According to Table 7, if a discriminator is not used, the model performance often decreases. Does that mean that the modifier cannot produce good prompt modifications, but instead relies on multiple attempts and using adversarial loss to select the best prompt? How to ensure that prompt modifications generated by the modifier are available?

Looking forward to your reply! Thank you!

**Comment by dxlong2000** [comment]
Hi @JasonCZH4, thank you for your question. 

- Deactivating the Discriminator doesn't necessarily mean that the performance decrease is due to the Prompt Modifier. Instead, the process for selecting the best prompt at each iteration changes when the Discriminator is turned off.

- Since the Prompt Modifier is powered by an LLM, the suggested modifications are always generatable.

Please let us know if you have further questions!
